version: 2

project_name: openapi-oathkeeper

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

gomod:
  proxy: true

checksum:
  name_template: "checksums.txt"

source:
  enabled: true

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip

snapshot:
  name_template: "{{ incpatch .Version }}-next"

sboms:
  - id: syft-archive
    artifacts: archive

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: "{{ .ProjectName }}"
    description: "This project aims to automating the generation of Ory Oathkeeper rules from an OpenAPI 3 contract and save a lot of time and effort, especially for larger projects with many endpoints or many services."
    license: "MIT"
    repository:
      owner: cerberauth
      name: "{{ .ProjectName }}"
    goarm: 6
    test: |
      system "#{bin}/{{ .ProjectName }} help"
    homepage: https://github.com/cerberauth/openapi-oathkeeper
    commit_author:
      name: emmanuelgautier
      email: emmanuel@cerberauth.com

# nfpms:
#   - package_name: "{{ .ProjectName }}"
#     vendor: CerberAuth
#     homepage: https://github.com/cerberauth/openapi-oathkeeper
#     maintainer: Emmanuel Gautier <emmanuel@cerberauth.com>
#     description: "This project aims to automating the generation of Ory Oathkeeper rules from an OpenAPI 3 contract and save a lot of time and effort, especially for larger projects with many endpoints or many services."
#     license: "MIT"
#     formats:
#       - apk
#       - deb
#       - rpm
#       - termux.deb
#       - archlinux

snapcrafts:
  - title: OpenAPI to Ory Oathkeeper rules
    publish: true
    summary: "Automating the generation of Ory Oathkeeper rules from OpenAPI"
    description: "This project aims to automating the generation of Ory Oathkeeper rules from an OpenAPI 3 contract and save a lot of time and effort, especially for larger projects with many endpoints or many services."
    license: MIT

dockers:
  - image_templates:
      - "cerberauth/openapi-oathkeeper:{{ .Tag }}"
      - "cerberauth/openapi-oathkeeper:v{{ .Major }}"
      - "cerberauth/openapi-oathkeeper:v{{ .Major }}.{{ .Minor }}"
      - "cerberauth/openapi-oathkeeper:latest"
      - "ghcr.io/cerberauth/openapi-oathkeeper:{{ .Tag }}"
      - "ghcr.io/cerberauth/openapi-oathkeeper:v{{ .Major }}"
      - "ghcr.io/cerberauth/openapi-oathkeeper:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/cerberauth/openapi-oathkeeper:latest"
    dockerfile: .docker/Dockerfile-goreleaser

docker_signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    artifacts: images
    output: true
    args:
      - "sign"
      - "${artifact}"
      - "--yes"
