# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: openapi-oathkeeper

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    mod_timestamp: "{{ .CommitTimestamp }}"

gomod:
  proxy: true

checksum:
  name_template: "checksums.txt"

source:
  enabled: true

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip

snapshot:
  name_template: "{{ incpatch .Version }}-next"

sboms:
  - id: syft-archive
    artifacts: archive

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - --yes
    artifacts: checksum
    output: true

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: "{{ .ProjectName }}"
    description: "This project aims to automating the generation of Ory Oathkeeper rules from an OpenAPI 3 contract and save a lot of time and effort, especially for larger projects with many endpoints or many services."
    license: "MIT"
    repository:
      owner: cerberauth
      name: "{{ .ProjectName }}"
    goarm: 6
    test: |
      system "#{bin}/{{ .ProjectName }} help"
    homepage: https://github.com/cerberauth/openapi-oathkeeper
    commit_author:
      name: emmanuelgautier
      email: emmanuel@cerberauth.com

nfpms:
  - package_name: "{{ .ProjectName }}"
    vendor: CerberAuth
    homepage: https://github.com/cerberauth/openapi-oathkeeper
    maintainer: Emmanuel Gautier <emmanuel@cerberauth.com>
    license: "MIT"
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux

snapcrafts:
  - title: OpenAPI to Ory Oathkeeper rules
    publish: true
    summary: "Automating the generation of Ory Oathkeeper rules from OpenAPI"
    description: "This project aims to automating the generation of Ory Oathkeeper rules from an OpenAPI 3 contract and save a lot of time and effort, especially for larger projects with many endpoints or many services."
    license: MIT

dockers_v2:
  - images:
      - "cerberauth/openapi-oathkeeper"
      - "ghcr.io/cerberauth/openapi-oathkeeper"
    dockerfile: .docker/Dockerfile-goreleaser
    tags:
      - "{{ .Tag }}"
      - v{{ .Major }}
      - v{{ .Major }}.{{ .Minor }}
      - latest
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

docker_signs:
  - cmd: cosign
    artifacts: manifests
    args:
      - "sign"
      - "${artifact}"
      - "--yes"

announce:
  twitter:
    enabled: false
    message_template: "nFPM {{ .Tag }} was just released! See what's new: https://github.com/goreleaser/nfpm/releases/tag/{{ .Tag }}"
  discord:
    enabled: true
    message_template: "nFPM {{ .Tag }} is out! See what's new: https://github.com/goreleaser/nfpm/releases/tag/{{ .Tag }}"
