FROM gcr.io/distroless/static-debian12:nonroot

ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT

COPY --chown=nonroot:nonroot ${TARGETOS}/${TARGETARCH}${TARGETVARIANT:+/$TARGETVARIANT}/openapi-oathkeeper /usr/bin/openapi-oathkeeper

ENTRYPOINT ["/usr/bin/openapi-oathkeeper"]
